/**
 * Demo instrument — JSON motor (expandible; no lógica por prueba en código de negocio).
 * Las reglas de veredicto y flags viven en `scoring`.
 */
export const defaultDemoAssessmentConfig = {
  version: 1,
  meta: {
    title: 'Batería de Honestidad y Confianza (demo)',
    introSubtitle:
      'Esta evaluación mide valores, ética y comportamiento en situaciones laborales y personales.',
    timeLimitSec: 2700,
  },
  dimensions: [
    {
      id: 'honestidad',
      label: 'Honestidad',
      questionIds: ['p9', 'p20', 'p25', 'p27', 'p32', 'p33', 'p34', 'p40'],
    },
    {
      id: 'etica',
      label: 'Ética Personal y Prof.',
      questionIds: ['p2', 'p13', 'p17', 'p19', 'p21', 'p22', 'p23', 'p24', 'p38'],
    },
    {
      id: 'responsabilidad',
      label: 'Responsabilidad',
      questionIds: ['p6', 'p10', 'p12', 'p15', 'p16', 'p29', 'p35', 'p36', 'p37'],
    },
    { id: 'lealtad', label: 'Lealtad', questionIds: ['p1', 'p3', 'p4', 'p7', 'p8', 'p28', 'p31', 'p39'] },
    { id: 'integridad', label: 'Integridad', questionIds: ['p5', 'p11', 'p14', 'p18', 'p26', 'p30'] },
  ],
  sections: [
    {
      id: 'calibracion',
      title: 'Verificación de Atención',
      description:
        'Responde estas preguntas de calentamiento con atención. No afectan el puntaje final.',
      questions: [
        {
          id: 'c1',
          kind: 'calibration',
          labelType: 'Verificación',
          prompt: '¿Cuál es el día de la semana que sigue después del lunes?',
          options: ['Martes', 'Jueves', 'Domingo', 'Viernes'],
          correctIndex: 0,
        },
        {
          id: 'c2',
          kind: 'calibration',
          labelType: 'Verificación',
          prompt: '¿Qué color resulta de mezclar azul y amarillo?',
          options: ['Verde', 'Rojo', 'Morado', 'Naranja'],
          correctIndex: 0,
        },
        {
          id: 'c3',
          kind: 'calibration',
          labelType: 'Verificación',
          prompt: '¿Cuántas patas tiene un perro?',
          options: ['Cuatro', 'Dos', 'Tres', 'Seis'],
          correctIndex: 0,
        },
        {
          id: 'c4',
          kind: 'calibration',
          labelType: 'Verificación',
          prompt: 'Si tienes tres manzanas y das una, ¿cuántas te quedan?',
          options: ['Dos', 'Una', 'Tres', 'Ninguna'],
          correctIndex: 0,
        },
        {
          id: 'c5',
          kind: 'calibration',
          labelType: 'Verificación',
          prompt: '¿Cuál es el nombre del planeta en el que vivimos?',
          options: ['Tierra', 'Marte', 'Venus', 'Júpiter'],
          correctIndex: 0,
        },
      ],
    },
    {
      id: 'directas',
      title: 'Preguntas Directas',
      description: 'Responde con sinceridad sobre situaciones cotidianas personales.',
      questions: [
        {
          id: 'd1',
          kind: 'direct',
          labelType: 'Honestidad Directa',
          prompt: '¿Alguna vez has dicho una mentira, incluso si fue por una razón menor?',
          options: ['Sí, alguna vez.', 'No, nunca he mentido.', 'No recuerdo haber mentido.', 'Solo en situaciones muy necesarias.'],
          scoreByIndex: [100, 0, 25, 50],
          denialOptionIndex: 1,
        },
        {
          id: 'd2',
          kind: 'direct',
          labelType: 'Honestidad Directa',
          prompt: '¿Te has llevado algo que no era tuyo, incluso si era de poco valor?',
          options: ['Sí, alguna vez.', 'No, nunca.', 'Solo por error.', 'No estoy seguro.'],
          scoreByIndex: [100, 0, 50, 25],
          denialOptionIndex: 1,
        },
        {
          id: 'd3',
          kind: 'direct',
          labelType: 'Honestidad Directa',
          prompt: '¿Alguna vez has ocultado información importante para evitar problemas?',
          options: ['Sí, alguna vez.', 'No, siempre soy completamente transparente.', 'Solo si no era grave.', 'Prefiero no responder.'],
          scoreByIndex: [100, 0, 50, 25],
          denialOptionIndex: 1,
        },
        {
          id: 'd4',
          kind: 'direct',
          labelType: 'Honestidad Directa',
          prompt: '¿Te has aprovechado alguna vez de la confianza de alguien?',
          options: ['Sí, alguna vez.', 'No, nunca.', 'Solo en situaciones justificadas.', 'No estoy seguro.'],
          scoreByIndex: [100, 0, 50, 25],
          denialOptionIndex: 1,
        },
        {
          id: 'd5',
          kind: 'direct',
          labelType: 'Honestidad Directa',
          prompt: '¿Alguna vez has tomado un atajo que sabías que era incorrecto, pero que te beneficiaba?',
          options: ['Sí, alguna vez.', 'No, nunca.', 'Solo si no afectaba a otros.', 'Prefiero no decirlo.'],
          scoreByIndex: [100, 0, 50, 25],
          denialOptionIndex: 1,
        },
      ],
    },
    {
      id: 'principal',
      title: 'Evaluación Principal',
      description: 'Lee cada situación y elige la respuesta que mejor refleje tu comportamiento real.',
      questions: [
        {
          id: 'p1',
          kind: 'likert',
          labelType: 'Lealtad',
          dimension: 'lealtad',
          prompt: 'Imagina que estás en un supermercado y la cajera te da más cambio del que te corresponde. ¿Qué harías?',
          options: ['Devolverlo inmediatamente.', 'Guardar el dinero sin decir nada.', 'Guardarlo y donarlo a la caridad.', 'Pensarlo y quizás devolverlo después.'],
          scoreByIndex: [100, 0, 50, 75],
        },
        {
          id: 'p2',
          kind: 'likert',
          labelType: 'Ética',
          dimension: 'etica',
          prompt: 'Un amigo te pide que lo cubras en su trabajo porque quiere irse temprano. Sabes que si lo haces, podrías meterlo en problemas. ¿Qué harías?',
          options: ['Decirle que no lo harás.', 'Cubrirlo, pero sólo si no hay riesgos.', 'Cubrirlo sin pensarlo.', 'Sugerirle que pida permiso en lugar de irse.'],
          scoreByIndex: [100, 50, 0, 75],
        },
        {
          id: 'p3',
          kind: 'likert',
          labelType: 'Lealtad',
          dimension: 'lealtad',
          prompt: 'En una discusión, alguien te acusa injustamente de algo. ¿Cuál es tu reacción más probable?',
          options: ['Defenderte y explicar los hechos.', 'Callarte y dejar que las cosas pasen.', 'Enfrentar a la persona directamente.', 'Dejar que otros tomen la palabra por ti.'],
          scoreByIndex: [100, 50, 75, 25],
        },
        {
          id: 'p4',
          kind: 'likert',
          labelType: 'Lealtad',
          dimension: 'lealtad',
          prompt: 'Si descubres un error en tu cuenta bancaria que te beneficia, ¿qué harías?',
          options: ['Notificar al banco inmediatamente.', 'Esperar un tiempo a ver si lo corrigen.', 'Mantener el dinero.', 'Usarlo y luego devolverlo si lo solicitan.'],
          scoreByIndex: [100, 50, 0, 25],
        },
        {
          id: 'p5',
          kind: 'likert',
          labelType: 'Integridad',
          dimension: 'integridad',
          prompt: 'Te ofrecen un puesto que implica trabajar con información confidencial. ¿Cómo manejarías esta responsabilidad?',
          options: ['Sería muy cuidadoso con la información.', 'Sólo la compartiría si es absolutamente necesario.', 'Lo manejaría como cualquier otra información.', 'No me preocuparía demasiado por eso.'],
          scoreByIndex: [100, 75, 50, 25],
        },
        {
          id: 'p6',
          kind: 'likert',
          labelType: 'Responsabilidad',
          dimension: 'responsabilidad',
          prompt: 'Estás trabajando en un proyecto grupal y uno de tus compañeros no está cumpliendo con su parte. ¿Qué harías?',
          options: ['Hablar directamente con la persona.', 'Informar al líder del grupo.', 'Ignorarlo y hacer tu parte.', 'Cubrir su trabajo sin decir nada.'],
          scoreByIndex: [100, 75, 50, 25],
        },
        {
          id: 'p7',
          kind: 'likert',
          labelType: 'Lealtad',
          dimension: 'lealtad',
          prompt: 'Te ofrecen un descuento adicional por un error en la factura de una tienda. ¿Qué haces?',
          options: ['Informar del error al encargado.', 'Aprovechar el descuento sin decir nada.', 'Preguntar si es correcto el descuento.', 'Usarlo y si preguntan, negar conocimiento.'],
          scoreByIndex: [100, 0, 75, 25],
        },
        {
          id: 'p8',
          kind: 'likert',
          labelType: 'Lealtad',
          dimension: 'lealtad',
          prompt: 'Un colega te pide que firmes un documento en su nombre. ¿Cuál sería tu respuesta?',
          options: ['Decir que no puedes hacerlo.', 'Firmar solo si es urgente.', 'Firmar sin pensarlo.', 'Consultar con alguien más antes de hacerlo.'],
          scoreByIndex: [100, 50, 0, 75],
        },
        {
          id: 'p9',
          kind: 'likert',
          labelType: 'Honestidad',
          dimension: 'honestidad',
          prompt: 'Estás en una fiesta y alguien te cuenta un chisme sobre un amigo cercano. ¿Cómo reaccionas?',
          options: ['Defiendo a mi amigo.', 'Escucho pero no lo comparto.', 'Lo cuento a otro amigo después.', 'Lo ignoro completamente.'],
          scoreByIndex: [100, 75, 25, 50],
        },
        {
          id: 'p10',
          kind: 'likert',
          labelType: 'Responsabilidad',
          dimension: 'responsabilidad',
          prompt: 'Encuentras un objeto valioso en un lugar público sin dueño visible. ¿Qué harías?',
          options: ['Llevarlo a la oficina de objetos perdidos.', 'Guardarlo esperando que alguien lo reclame.', 'Quedártelo.', 'Intentar buscar al dueño.'],
          scoreByIndex: [100, 50, 0, 75],
        },
        {
          id: 'p11',
          kind: 'likert',
          labelType: 'Integridad',
          dimension: 'integridad',
          prompt: 'En tu trabajo, descubres que alguien más está recibiendo el crédito por tu esfuerzo. ¿Qué harías?',
          options: ['Hablar con tu jefe sobre la situación.', 'Dejar que las cosas sigan así.', 'Confrontar a la persona directamente.', 'Buscar reconocimiento en otra área.'],
          scoreByIndex: [100, 50, 75, 25],
        },
        {
          id: 'p12',
          kind: 'likert',
          labelType: 'Responsabilidad',
          dimension: 'responsabilidad',
          prompt: 'Te piden que firmes un contrato que no has tenido tiempo de leer. ¿Cómo actúas?',
          options: ['Pedir más tiempo para leerlo.', 'Firmarlo sin leer para no retrasar el proceso.', 'Leer solo las partes importantes.', 'Consultar a alguien antes de firmarlo.'],
          scoreByIndex: [100, 0, 50, 75],
        },
        {
          id: 'p13',
          kind: 'likert',
          labelType: 'Ética',
          dimension: 'etica',
          prompt: 'Un compañero de trabajo te pide ayuda para cubrir un error suyo. ¿Qué haces?',
          options: ['Lo ayudas pero informas al jefe.', 'Lo ayudas y lo mantienes en secreto.', 'No lo ayudas y le sugieres que lo enfrente.', 'Lo ignoras y dejas que lo resuelva solo.'],
          scoreByIndex: [75, 50, 100, 25],
        },
        {
          id: 'p14',
          kind: 'likert',
          labelType: 'Integridad',
          dimension: 'integridad',
          prompt: 'Estás en una reunión y escuchas que alguien está siendo menospreciado injustamente. ¿Cómo actúas?',
          options: ['Defiendo a la persona injustamente tratada.', 'Ignoro la situación.', 'Apoyo a la mayoría aunque no esté de acuerdo.', 'Cambio de tema para evitar el conflicto.'],
          scoreByIndex: [100, 25, 0, 50],
        },
        {
          id: 'p15',
          kind: 'likert',
          labelType: 'Responsabilidad',
          dimension: 'responsabilidad',
          prompt: 'Si fueras testigo de un pequeño robo en una tienda, ¿qué harías?',
          options: ['Informaría inmediatamente al personal.', 'No haría nada, no es asunto mío.', 'Esperaría a ver qué hacen los demás.', 'Informaría sólo si me preguntan.'],
          scoreByIndex: [100, 0, 25, 50],
        },
        {
          id: 'p16',
          kind: 'likert',
          labelType: 'Responsabilidad',
          dimension: 'responsabilidad',
          prompt: 'Un compañero de trabajo te pide que lo cubras en un tema en el que sabes que está mintiendo. ¿Qué harías?',
          options: ['Negarte a ayudarlo.', 'Ayudarlo solo si no hay riesgos.', 'Ayudarlo sin preguntar.', 'Informar a alguien más de la situación.'],
          scoreByIndex: [100, 50, 0, 75],
        },
        {
          id: 'p17',
          kind: 'likert',
          labelType: 'Ética',
          dimension: 'etica',
          prompt: 'Si te piden que cumplas una tarea para la cual no te sientes capacitado, ¿cómo reaccionas?',
          options: ['Admito mi falta de experiencia y pido ayuda.', 'Intento hacerla de todas formas.', 'La delego a otra persona.', 'La rechazo inmediatamente.'],
          scoreByIndex: [100, 50, 75, 25],
        },
        {
          id: 'p18',
          kind: 'likert',
          labelType: 'Integridad',
          dimension: 'integridad',
          prompt: 'Alguien te confía un secreto importante que podría afectar a muchas personas. ¿Cómo actúas?',
          options: ['Guardarlo y no decir nada.', 'Compartirlo solo con alguien de confianza.', 'Contarlo si es necesario para evitar daños.', 'Divulgarlo discretamente.'],
          scoreByIndex: [100, 50, 75, 0],
        },
        {
          id: 'p19',
          kind: 'likert',
          labelType: 'Ética',
          dimension: 'etica',
          prompt: 'En tu trabajo, te ofrecen una oportunidad de ascenso por un proyecto que realmente no hiciste tú. ¿Qué haces?',
          options: ['Acepto el ascenso, pero aclaro el malentendido.', 'Acepto el ascenso sin decir nada.', 'Rechazo el ascenso hasta que se aclare la situación.', 'Acepto y comparto el crédito con quien corresponde.'],
          scoreByIndex: [75, 0, 100, 50],
        },
        {
          id: 'p20',
          kind: 'likert',
          labelType: 'Honestidad',
          dimension: 'honestidad',
          prompt: 'Un cliente te pide que modifiques ligeramente un documento para que sea más favorable para él. ¿Qué haces?',
          options: ['Me niego a hacer la modificación.', 'Lo hago, pero informo a mi supervisor.', 'Lo hago sin pensarlo mucho.', 'Sugiero un cambio más aceptable.'],
          scoreByIndex: [100, 75, 0, 50],
        },
        {
          id: 'p21',
          kind: 'likert',
          labelType: 'Ética',
          dimension: 'etica',
          prompt: 'Te enteras de que tu empresa está en una situación financiera difícil y podrían ocurrir despidos. ¿Cómo actúas?',
          options: ['Mantengo la calma y continúo trabajando como siempre.', 'Empiezo a buscar un nuevo trabajo de inmediato.', 'Informo a otros sobre la situación.', 'Tomo precauciones pero sigo mi rutina.'],
          scoreByIndex: [100, 50, 25, 75],
        },
        {
          id: 'p22',
          kind: 'likert',
          labelType: 'Ética',
          dimension: 'etica',
          prompt: 'Si tienes que trabajar con alguien que sabes que es deshonesto, ¿cómo te comportarías?',
          options: ['Mantengo la relación profesional pero vigilante.', 'Me alejo lo más posible de esa persona.', 'Trabajo con él sin importar su reputación.', 'Intento confrontarlo sobre su comportamiento.'],
          scoreByIndex: [75, 100, 50, 100],
        },
        {
          id: 'p23',
          kind: 'likert',
          labelType: 'Ética',
          dimension: 'etica',
          prompt: 'Si un conocido te pide que le ayudes en algo ilegal, ¿qué harías?',
          options: ['Negarme rotundamente.', 'Lo consideraría dependiendo de las circunstancias.', 'Ayudaría si no hay riesgo.', 'Lo haría, pero bajo condiciones.'],
          scoreByIndex: [100, 50, 25, 0],
        },
        {
          id: 'p24',
          kind: 'likert',
          labelType: 'Ética',
          dimension: 'etica',
          prompt: 'En una situación de crisis, ¿cómo sueles tomar decisiones?',
          options: ['Tomo decisiones rápidas basadas en principios.', 'Me tomo el tiempo necesario para reflexionar.', 'Sigo la mayoría o lo que otros hagan.', 'Evito tomar decisiones hasta que sea necesario.'],
          scoreByIndex: [75, 100, 50, 25],
        },
        {
          id: 'p25',
          kind: 'likert',
          labelType: 'Honestidad',
          dimension: 'honestidad',
          prompt: 'Si un amigo te ofrece una oportunidad para ganar dinero rápidamente pero sospechas que no es del todo legal, ¿qué harías?',
          options: ['Rechazar la oferta.', 'Considerar la oferta antes de decidir.', 'Aceptar si no hay riesgo de ser descubierto.', 'Aceptar, pero pedir más detalles antes.'],
          scoreByIndex: [100, 50, 0, 25],
        },
        {
          id: 'p26',
          kind: 'likert',
          labelType: 'Integridad',
          dimension: 'integridad',
          prompt: 'Te ofrecen un regalo a cambio de un favor en tu trabajo. ¿Cómo reaccionas?',
          options: ['Rechazo el regalo y explico por qué.', 'Acepto el regalo pero no hago el favor.', 'Acepto y hago el favor.', 'Rechazo el regalo pero ofrezco ayuda dentro de las reglas.'],
          scoreByIndex: [100, 50, 0, 75],
        },
        {
          id: 'p27',
          kind: 'likert',
          labelType: 'Honestidad',
          dimension: 'honestidad',
          prompt: 'Un colega te pide que mientas para cubrirlo en una situación complicada. ¿Qué haces?',
          options: ['Me niego a mentir.', 'Miento solo si no hay riesgo.', 'Miento para ayudarlo sin pensarlo mucho.', 'Le sugiero una solución alternativa.'],
          scoreByIndex: [100, 50, 0, 75],
        },
        {
          id: 'p28',
          kind: 'likert',
          labelType: 'Lealtad',
          dimension: 'lealtad',
          prompt: 'Te das cuenta de que cometiste un error en un proyecto importante. ¿Cómo lo manejas?',
          options: ['Informo inmediatamente a mi supervisor.', 'Intento corregirlo sin decir nada.', 'Lo dejo pasar y espero que nadie lo note.', 'Consulto con un colega antes de tomar una decisión.'],
          scoreByIndex: [100, 75, 0, 50],
        },
        {
          id: 'p29',
          kind: 'likert',
          labelType: 'Responsabilidad',
          dimension: 'responsabilidad',
          prompt: 'Si recibes información confidencial de manera accidental, ¿qué haces?',
          options: ['No la comparto y la devuelvo a su dueño.', 'La leo pero no la uso.', 'La comparto con alguien de confianza.', 'La uso si me beneficia.'],
          scoreByIndex: [100, 50, 25, 0],
        },
        {
          id: 'p30',
          kind: 'likert',
          labelType: 'Integridad',
          dimension: 'integridad',
          prompt: 'En una competencia, descubres que un contrincante está haciendo trampa. ¿Cómo reaccionas?',
          options: ['Informo a los organizadores de inmediato.', 'No hago nada, que se encarguen otros.', 'Trato de ganar a pesar de la trampa.', 'Intento hacer trampa también para equilibrar.'],
          scoreByIndex: [100, 25, 75, 0],
        },
        {
          id: 'p31',
          kind: 'likert',
          labelType: 'Lealtad',
          dimension: 'lealtad',
          prompt: 'Te das cuenta de que alguien está siendo acosado en tu entorno laboral. ¿Qué haces?',
          options: ['Informo a Recursos Humanos o al supervisor.', 'Hablo con la persona afectada para apoyarla.', 'Ignoro la situación para evitar problemas.', 'Hago lo que pueda sin involucrarme directamente.'],
          scoreByIndex: [100, 75, 25, 50],
        },
        {
          id: 'p32',
          kind: 'likert',
          labelType: 'Honestidad',
          dimension: 'honestidad',
          prompt: 'Un cliente te pide que hagas algo que sabes que va en contra de la política de la empresa. ¿Qué haces?',
          options: ['Me niego y explico por qué.', 'Lo hago si no hay riesgo de ser descubierto.', 'Busco una solución alternativa dentro de las reglas.', 'Lo hago y después me aseguro de cubrirlo.'],
          scoreByIndex: [100, 25, 75, 0],
        },
        {
          id: 'p33',
          kind: 'likert',
          labelType: 'Honestidad',
          dimension: 'honestidad',
          prompt: 'Te enteras de que un colega ha hecho algo que podría causar un problema serio en el trabajo. ¿Qué haces?',
          options: ['Informo a la persona responsable de inmediato.', 'Hablo con el colega para que lo resuelva.', 'Ignoro la situación y sigo con mi trabajo.', 'Lo resuelvo por mi cuenta sin decir nada.'],
          scoreByIndex: [100, 75, 25, 50],
        },
        {
          id: 'p34',
          kind: 'likert',
          labelType: 'Honestidad',
          dimension: 'honestidad',
          prompt: 'Estás trabajando en un equipo donde alguien no está haciendo su parte. ¿Qué harías?',
          options: ['Hablo con la persona y ofrezco ayuda.', 'Informo al líder del equipo.', 'Ignoro la situación y hago mi trabajo.', 'Hago su trabajo para que el equipo no se vea afectado.'],
          scoreByIndex: [100, 75, 50, 25],
        },
        {
          id: 'p35',
          kind: 'likert',
          labelType: 'Responsabilidad',
          dimension: 'responsabilidad',
          prompt: 'Te ofrecen la oportunidad de ganar un bono si alcanzas un objetivo poco realista. ¿Qué haces?',
          options: ['Trabajo duro para alcanzarlo aunque sea difícil.', 'Intento alcanzarlo pero sin comprometer la calidad.', 'Hago lo que sea necesario para lograrlo.', 'Renuncio al bono y hago mi trabajo habitual.'],
          scoreByIndex: [100, 75, 50, 25],
        },
        {
          id: 'p36',
          kind: 'likert',
          labelType: 'Lealtad',
          dimension: 'lealtad',
          prompt: 'Un colega que es amigo personal tuyo comete un error que afecta a toda la empresa. ¿Cómo reaccionas?',
          options: ['Lo informo a quien corresponde.', 'Hablo con él y le sugiero que lo reporte.', 'Lo ayudo a encubrirlo.', 'Lo ignoro para proteger nuestra amistad.'],
          scoreByIndex: [100, 75, 25, 50],
        },
        {
          id: 'p37',
          kind: 'likert',
          labelType: 'Responsabilidad',
          dimension: 'responsabilidad',
          prompt: 'Te enteras de que un proveedor con el que trabajas regularmente está involucrado en actividades poco éticas. ¿Qué haces?',
          options: ['Informo a mi empresa y sugiero cambiar de proveedor.', 'Continuo trabajando con él pero con precaución.', 'Ignoro la situación mientras me beneficie.', 'Intento confrontarlo y pedir explicaciones.'],
          scoreByIndex: [100, 50, 25, 75],
        },
        {
          id: 'p38',
          kind: 'likert',
          labelType: 'Ética',
          dimension: 'etica',
          prompt: 'Si descubres que la empresa para la que trabajas está involucrada en actividades ilegales, ¿qué harías?',
          options: ['Renuncio inmediatamente y lo denuncio.', 'Continuo trabajando mientras busco otra opción.', 'No hago nada si no me afecta personalmente.', 'Intento hacer lo correcto desde dentro.'],
          scoreByIndex: [100, 50, 25, 75],
        },
        {
          id: 'p39',
          kind: 'likert',
          labelType: 'Lealtad',
          dimension: 'lealtad',
          prompt: 'En un evento social, alguien comienza a hacer comentarios inapropiados sobre un compañero de trabajo. ¿Cómo reaccionas?',
          options: ['Defiendo al compañero y detengo los comentarios.', 'Ignoro los comentarios y me alejo.', 'Sigo el juego para no causar problemas.', 'Hablo con el compañero afectado en privado.'],
          scoreByIndex: [100, 50, 25, 75],
        },
        {
          id: 'p40',
          kind: 'likert',
          labelType: 'Honestidad',
          dimension: 'honestidad',
          prompt: 'Te enteras de que alguien está manipulando los resultados de una evaluación en el trabajo. ¿Qué haces?',
          options: ['Informo de inmediato a las autoridades pertinentes.', 'Confronto a la persona directamente.', 'Lo ignoro si no me afecta directamente.', 'Intento arreglar el problema sin que se sepa.'],
          scoreByIndex: [100, 75, 25, 50],
        },
      ],
    },
  ],
  scoring: {
    flags: [
      {
        id: 'calibration_attention',
        when: { kind: 'calibration_errors_gt', value: 1 },
        messageTemplate: 'Atención reducida detectada: {{errCal}} errores en preguntas de verificación.',
      },
      {
        id: 'denial_pattern',
        when: { kind: 'direct_denials_gte', value: 3 },
        messageTemplate:
          'Patrón de negación detectado: respuestas estadísticamente improbables sugieren posible manipulación de resultados.',
      },
    ],
    verdictRules: [
      {
        priority: 1,
        verdict: 'No Aprobatorio',
        badge: '⚠️ No Aprobatorio',
        descriptionTemplate:
          'Puntaje global: {{global}}%. Las competencias críticas de Honestidad ({{honPct}}%) y/o Ética ({{etPct}}%) están por debajo del umbral mínimo del 70%.',
        match: {
          op: 'or',
          items: [
            { op: 'lt', left: { kind: 'dimensionAvg', id: 'honestidad' }, right: 70 },
            { op: 'lt', left: { kind: 'dimensionAvg', id: 'etica' }, right: 70 },
          ],
        },
      },
      {
        priority: 2,
        verdict: 'No Aprobatorio',
        badge: '⚠️ No Aprobatorio',
        descriptionTemplate: 'El puntaje global de {{global}}% está por debajo del umbral mínimo requerido del 50%.',
        match: { op: 'lt', left: { kind: 'globalAvg' }, right: 50 },
      },
      {
        priority: 3,
        verdict: 'Aprobatorio con Reservas',
        badge: '📋 Con Reservas',
        descriptionTemplate:
          'Puntaje global: {{global}}%. El candidato cumple requisitos mínimos. Se recomienda análisis adicional en áreas de riesgo.',
        match: { op: 'lt', left: { kind: 'globalAvg' }, right: 75 },
      },
      {
        priority: 4,
        verdict: 'Aprobatorio',
        badge: '✅ Aprobatorio',
        descriptionTemplate:
          'Excelente resultado. Puntaje global de {{global}}% supera el umbral aprobatorio (75%). El candidato demuestra sólidos valores de honestidad e integridad.',
        match: { op: 'true' },
      },
    ],
  },
};
